name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10", "pypy3"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e flake8

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e black

  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install gitlint
        run: pip install gitlint
      - name: Run gitlint
        run: gitlint --contrib contrib-title-conventional-commits
